development:
  adapter: redis
  url: <%= "#{ENV['REDISCLOUD_URL']}/1" %>
  channel_prefix: articles

test:
  adapter: test

production:
  adapter: redis
  url: <%= "#{ENV['REDISCLOUD_URL']}/1"%>
  channel_prefix: articles
