development:
  adapter: redis
  url: <%= "#{ENV['REDISCLOUD_URL']}" %>
  channel_prefix: articles

test:
  adapter: test

production:
  adapter: redis
  url: <%= "#{ENV['REDISCLOUD_URL']}"%>
  channel_prefix: articles
