
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: localhost
  user: <%= ENV['DB_PG_USER'] %>
  password: <%= ENV['DB_PG_PASSWORD'] %>
  database: beckend_development

test:
  <<: *default
  host: localhost
  user: <%= ENV['DB_PG_USER'] %>
  password: <%= ENV['DB_PG_PASSWORD'] %>
  database: beckend_test

production:
  <<: *default
  host: localhost
  user: <%= ENV['DB_PG_USER'] %>
  password: <%= ENV['DB_PG_PASSWORD'] %>
  database: beckend_prodaction
